import React from 'react';
import { InterviewFeedback, Message } from '../types';
import { motion } from 'framer-motion';
import { CheckCircle, XCircle, Award, BookOpen, Download, FileText } from 'lucide-react';

interface FeedbackReportProps {
  feedback: InterviewFeedback | null;
  isLoading: boolean;
  onRestart: () => void;
  messages: Message[];
}

const ScoreCard = ({ title, score, delay }: { title: string, score: number, delay: number }) => (
    <motion.div 
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay }}
        className="bg-slate-800 p-4 rounded-xl border border-slate-700 flex flex-col items-center justify-center"
    >
        <div className="text-3xl font-bold mb-1 text-white">{score}<span className="text-sm text-slate-500">/10</span></div>
        <div className="text-xs text-slate-400 uppercase tracking-wider text-center">{title}</div>
        <div className="w-full h-1 bg-slate-700 mt-3 rounded-full overflow-hidden">
            <motion.div 
                initial={{ width: 0 }}
                animate={{ width: `${score * 10}%` }}
                transition={{ delay: delay + 0.3, duration: 1 }}
                className={`h-full ${score >= 7 ? 'bg-green-500' : score >= 5 ? 'bg-yellow-500' : 'bg-red-500'}`}
            />
        </div>
    </motion.div>
)

const FeedbackReport: React.FC<FeedbackReportProps> = ({ feedback, isLoading, onRestart, messages }) => {
  if (isLoading) {
    return (
        <div className="min-h-screen bg-slate-900 text-white flex flex-col items-center justify-center p-6 text-center">
            <div className="w-16 h-16 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mb-6"></div>
            <h2 className="text-2xl font-bold mb-2">Generating Comprehensive Report...</h2>
            <p className="text-slate-400">Analyzing transcript, evaluating technical accuracy, and scoring soft skills.</p>
        </div>
    )
  }

  if (!feedback) return null;

  const handleDownloadTranscript = () => {
    const text = messages.map(m => `[${new Date(m.timestamp).toLocaleTimeString()}] ${m.role === 'user' ? 'Candidate' : 'Interviewer'}: ${m.text}`).join('\n\n');
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `interview-transcript-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8">
      <div className="max-w-5xl mx-auto space-y-8">
        
        <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
                <h1 className="text-3xl font-bold">Interview Performance Report</h1>
                <p className="text-slate-400">Generated by MockMate AI • {new Date().toLocaleDateString()}</p>
            </div>
            <div className="flex gap-3 flex-wrap">
                <button onClick={onRestart} className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 transition border border-slate-700">
                    New Interview
                </button>
                <button onClick={handleDownloadTranscript} className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 transition flex items-center gap-2 border border-slate-700 text-slate-200">
                    <FileText size={16} /> Download Transcript
                </button>
                <button className="px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white flex items-center gap-2">
                    <Download size={16} /> Export PDF
                </button>
            </div>
        </header>

        {/* Scores Grid */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
            <ScoreCard title="Communication" score={feedback.scores.communication} delay={0.1} />
            <ScoreCard title="Technical" score={feedback.scores.technical} delay={0.2} />
            <ScoreCard title="Problem Solving" score={feedback.scores.problemSolving} delay={0.3} />
            <ScoreCard title="Cultural Fit" score={feedback.scores.culturalFit} delay={0.4} />
            <motion.div 
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.5 }}
                className="bg-gradient-to-br from-blue-600 to-indigo-700 p-4 rounded-xl border border-blue-400/30 flex flex-col items-center justify-center shadow-lg shadow-blue-900/40"
            >
                <div className="text-4xl font-bold mb-1 text-white">{feedback.scores.overall}</div>
                <div className="text-xs text-blue-100 uppercase tracking-wider">Overall Score</div>
            </motion.div>
        </div>

        {/* Summary */}
        <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            className="bg-slate-900 border border-slate-800 p-6 rounded-2xl"
        >
            <h3 className="text-xl font-semibold mb-4 flex items-center gap-2"><Award className="text-yellow-500"/> Executive Summary</h3>
            <p className="text-slate-300 leading-relaxed">
                {feedback.summary}
            </p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-8">
            {/* Strengths */}
            <motion.div 
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.7 }}
                className="bg-slate-900/50 border border-slate-800 p-6 rounded-2xl"
            >
                <h3 className="text-xl font-semibold mb-4 text-green-400 flex items-center gap-2"><CheckCircle size={20}/> Key Strengths</h3>
                <ul className="space-y-3">
                    {feedback.strengths.map((item, i) => (
                        <li key={i} className="flex gap-3 text-slate-300">
                            <span className="w-1.5 h-1.5 bg-green-500 rounded-full mt-2 shrink-0"/>
                            {item}
                        </li>
                    ))}
                </ul>
            </motion.div>

            {/* Improvements */}
            <motion.div 
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.8 }}
                className="bg-slate-900/50 border border-slate-800 p-6 rounded-2xl"
            >
                <h3 className="text-xl font-semibold mb-4 text-red-400 flex items-center gap-2"><XCircle size={20}/> Areas for Improvement</h3>
                 <ul className="space-y-3">
                    {feedback.improvements.map((item, i) => (
                        <li key={i} className="flex gap-3 text-slate-300">
                             <span className="w-1.5 h-1.5 bg-red-500 rounded-full mt-2 shrink-0"/>
                            {item}
                        </li>
                    ))}
                </ul>
            </motion.div>
        </div>

        {/* Recommendations */}
        <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.9 }}
            className="bg-indigo-900/20 border border-indigo-500/20 p-6 rounded-2xl"
        >
             <h3 className="text-xl font-semibold mb-4 text-indigo-400 flex items-center gap-2"><BookOpen size={20}/> Recommended Actions</h3>
             <div className="grid md:grid-cols-2 gap-4">
                 {feedback.recommendations.map((rec, i) => (
                     <div key={i} className="bg-slate-800 p-4 rounded-lg text-sm text-slate-300 border border-slate-700">
                         {rec}
                     </div>
                 ))}
             </div>
        </motion.div>

      </div>
    </div>
  );
};

export default FeedbackReport;